"""Add foreign key for artist and song

Revision ID: 78685c029fb5
Revises: 91660e97dd4f
Create Date: 2019-08-31 12:26:07.640940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78685c029fb5'
down_revision = '91660e97dd4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('artist', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'songs', 'artists', ['artist'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'songs', type_='foreignkey')
    op.drop_column('songs', 'artist')
    # ### end Alembic commands ###
